org: ricardoamiel
service: api-s3

provider:
  name: aws
  runtime: python3.12
  memorySize: 256
  iam:
    role: arn:aws:iam::620587230140:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true
          integration: lambda
  crear_carpeta:
    handler: crear_carpeta.lambda_handler
    events:
      - http:
          path: /s3/crear-carpeta
          method: post
          cors: true
          integration: lambda